> Download and tidy up *real* data for training.

In [1]:
import pathlib
import os

import torch

import trapallada.xsa.access
import trapallada.xsa.util
import trapallada.data
import trapallada.plot

So that the notebook is aware of modifications in the the `import`ed modules

In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

The directory where observations' data will be saved

In [3]:
download_directory =  pathlib.Path(os.environ['MY_DATA_DIR']) / 'trapallada'
download_directory.mkdir(exist_ok=True)

That in which data will be saved

In [4]:
output_directory = pathlib.Path.cwd().parent / 'data'
assert output_directory.exists()

## Data for Javi's paper

In [5]:
javi_obs = '0605950101'
javi_obs_dir = trapallada.xsa.util.download_extract_filter(obs=javi_obs, output_directory=download_directory)
javi_obs_dir

trapallada.xsa.util - INFO - found file "/home/manu/data/trapallada/0605950101.tar", extracting...

found directory "/home/manu/data/trapallada/0605950101", skipping...

PosixPath('/home/manu/data/trapallada/0605950101')

The downloaded files

In [6]:
fits_files = list(javi_obs_dir.glob('*.FTZ'))
fits_files[:3]

[PosixPath('/home/manu/data/trapallada/0605950101/P0605950101PNS003SRCTSR802C.FTZ'),
 PosixPath('/home/manu/data/trapallada/0605950101/P0605950101PNS003SRCTSR8016.FTZ'),
 PosixPath('/home/manu/data/trapallada/0605950101/P0605950101PNS003SRCTSR801F.FTZ')]

In [7]:
df, skipped_files_list = trapallada.xsa.util.read_fits_files(fits_files)
print(f'len{skipped_files_list=}')
df.head()

lenskipped_files_list=[]

,P0605950101PNS003SRCTSR802C.FTZ,P0605950101PNS003SRCTSR8016.FTZ,P0605950101PNS003SRCTSR801F.FTZ,P0605950101PNS003SRCTSR8020.FTZ,P0605950101PNS003SRCTSR800F.FTZ,P0605950101PNS003SRCTSR802B.FTZ,P0605950101PNS003SRCTSR804C.FTZ,P0605950101PNS003SRCTSR8008.FTZ,P0605950101PNS003SRCTSR8018.FTZ,P0605950101PNS003SRCTSR8022.FTZ,...,P0605950101PNS003SRCTSR8064.FTZ,P0605950101PNS003SRCTSR8036.FTZ,P0605950101PNS003SRCTSR8030.FTZ,P0605950101PNS003SRCTSR8012.FTZ,P0605950101PNS003SRCTSR8021.FTZ,P0605950101PNS003SRCTSR801C.FTZ,P0605950101PNS003SRCTSR801A.FTZ,P0605950101PNS003SRCTSR8009.FTZ,P0605950101PNS003SRCTSR8002.FTZ,P0605950101PNS003SRCTSR8032.FTZ
TIME,,,,,,,,,,,,,,,,,,,,,
2009-06-03 08:10:33.517454,0.000000,0.0,-0.030024,0.0,0.000000,0.000000,0.0,0.837148,0.000000,0.0,...,0.00000,0.0,-0.02643,0.000000,0.0,0.0,-0.00934,-0.125560,0.808501,0.000000
2009-06-03 08:10:34.977454,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,...,-0.03712,0.0,0.00000,0.000000,0.0,0.0,0.00000,0.000000,0.771650,0.000000
2009-06-03 08:10:36.437454,0.000000,0.0,0.000000,0.0,-0.050389,-0.020843,0.0,0.000000,0.000000,0.0,...,0.00000,0.0,0.00000,0.000000,0.0,0.0,0.00000,0.000000,0.765734,0.000000
2009-06-03 08:10:37.897454,-0.010277,0.0,0.000000,0.0,0.000000,0.000000,0.0,-0.090626,-0.010292,0.0,...,0.00000,0.0,0.00000,0.000000,0.0,0.0,0.00000,0.778995,0.000000,0.000000
2009-06-03 08:10:39.357454,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,...,0.00000,0.0,0.00000,-0.104794,0.0,0.0,0.00000,0.000000,0.778009,-0.021274

We have `number of rows` measurements for each one of the `number of columns` signals

In [8]:
df.shape

(31805, 49)

The period is

In [9]:
df.index[1] - df.index[0]

Timedelta('0 days 00:00:01.460000')

Signals are *binned* so that a bunch of samples/measurements are added up together

In [10]:
# bin_size = 63
bin_size = 5
binned_df = trapallada.xsa.util.bin_fits_df(df, bin_size=bin_size)
binned_df

,P0605950101PNS003SRCTSR802C.FTZ,P0605950101PNS003SRCTSR8016.FTZ,P0605950101PNS003SRCTSR801F.FTZ,P0605950101PNS003SRCTSR8020.FTZ,P0605950101PNS003SRCTSR800F.FTZ,P0605950101PNS003SRCTSR802B.FTZ,P0605950101PNS003SRCTSR804C.FTZ,P0605950101PNS003SRCTSR8008.FTZ,P0605950101PNS003SRCTSR8018.FTZ,P0605950101PNS003SRCTSR8022.FTZ,...,P0605950101PNS003SRCTSR8064.FTZ,P0605950101PNS003SRCTSR8036.FTZ,P0605950101PNS003SRCTSR8030.FTZ,P0605950101PNS003SRCTSR8012.FTZ,P0605950101PNS003SRCTSR8021.FTZ,P0605950101PNS003SRCTSR801C.FTZ,P0605950101PNS003SRCTSR801A.FTZ,P0605950101PNS003SRCTSR8009.FTZ,P0605950101PNS003SRCTSR8002.FTZ,P0605950101PNS003SRCTSR8032.FTZ
TIME,,,,,,,,,,,,,,,,,,,,,
2009-06-03 08:10:40.817454,-0.010277,-0.024786,0.000000,0.000000,-0.050389,-0.020843,0.000000,-0.090626,-0.010292,0.00000,...,-0.037120,0.000000,0.000000,-0.104794,0.000000,0.000000,0.000000,0.778995,3.868380,-0.021274
2009-06-03 08:10:48.117454,-0.020634,0.784629,-0.024984,0.000000,0.000000,-0.048097,-0.054643,0.000000,-0.010478,0.00000,...,0.000000,-0.011943,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.339760,0.000000
2009-06-03 08:10:55.417454,-0.031101,0.000000,0.000000,-0.023497,0.000000,-0.021987,-0.024980,1.555758,0.000000,-0.02778,...,-0.075322,-0.011736,0.000000,0.000000,0.000000,-0.035350,-0.008848,0.000000,2.079360,-0.021407
2009-06-03 08:11:02.717454,-0.010495,0.000000,-0.024949,0.000000,-0.050300,0.000000,0.000000,0.692941,-0.031717,0.00000,...,0.000000,-0.011466,0.000000,0.000000,0.000000,-0.011912,0.000000,0.000000,7.150365,0.000000
2009-06-03 08:11:10.017454,0.000000,-0.050567,0.000000,0.000000,0.000000,-0.020697,-0.023514,0.000000,-0.010341,0.00000,...,-0.037728,-0.011562,-0.023484,0.000000,0.000000,0.000000,-0.017166,0.000000,5.450840,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2009-06-03 21:03:52.317454,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.800506,0.704297,0.000000,0.00000,...,0.000000,-0.011585,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.349519,0.000000
2009-06-03 21:03:59.617454,-0.020185,0.000000,0.000000,0.000000,1.503875,-0.020431,0.000000,-0.089011,-0.010376,0.00000,...,-0.037869,0.000000,-0.023281,0.788680,0.000000,0.000000,0.000000,0.000000,2.849825,-0.021557
2009-06-03 21:04:06.917454,0.000000,0.000000,0.000000,-0.026902,0.000000,0.000000,0.000000,-0.109253,-0.020772,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-0.013571,-0.008492,0.000000,2.341192,-0.021423
2009-06-03 21:04:14.217454,0.000000,0.000000,0.000000,0.000000,-0.105424,-0.043608,-0.049544,0.676927,-0.020948,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-0.012972,0.000000,-0.114098,0.519583,0.000000
2009-06-03 21:04:21.517454,0.000000,0.000000,0.000000,0.000000,-0.100765,-0.020841,-0.023770,0.521708,-0.020686,0.00000,...,-0.037390,0.000000,-0.023920,0.000000,-0.024854,-0.035537,0.000000,0.000000,1.560162,0.000000

The period is now

In [ ]:
binned_df.index[1] - binned_df.index[0]

Signals might have `NaN`s

In [ ]:
signals = binned_df.values.T
np.isnan(signals).sum()
# np.argwhere(np.isnan(signals))

if there are `NaN`s, they are fixed by interpolation

In [ ]:
if binned_df.isna().any().any():
    binned_df = binned_df.interpolate(method='linear', axis=0)

Output file...

In [ ]:
output_file = (output_directory / f'{javi_obs}_bin_size_{bin_size}').with_suffix('.pt')
output_file

...to save the signals (notice we add an extra *dummy* axis)

In [ ]:
torch.save(np.expand_dims(binned_df.values.T, 1), output_file)

A `SignalsDataset` is instantiated...

In [ ]:
ds = trapallada.data.SignalsDataset(output_file, metadata_filename=None, normalize=True)
len(ds)

...and plotted

In [ ]:
trapallada.plot.signals_dataset(ds, columns=[pathlib.Path(c).stem for c in df.columns], n_signals=None, n_samples=1_000)

A particular signal

In [ ]:
n_samples_to_plot = 2_000
sample_signal = binned_df['P0605950101PNS003SRCTSR8001.FTZ'].iloc[:n_samples_to_plot].values
trapallada.plot.signal(sample_signal)

# Dataset

**All** the observations in XSA whose duration is in the given interval are downloaded

In [ ]:
# trapallada.xsa.util.download_observations(download_directory=download_directory, duration_interval=(35_000, 45_000))

The *tar* files in the download directory

In [ ]:
tar_files = list(download_directory.glob('*.tar'))
tar_files[:3]

In [ ]:
fits_df = trapallada.xsa.util.read_tar(tar_files[2], max_n_sources=4)
fits_df

In [ ]:
fits_df.index[1] - fits_df.index[0]

If there is *any* `NaN` at all (in any column, at any time instant), it's filled in using interpolation.

In [ ]:
if fits_df.isna().any().any():
    print('Interpolating...')
    fits_df = fits_df.interpolate(method='linear', axis=0)

In [ ]:
bin_size = 63
# bin_size = 32
binned_df = trapallada.xsa.util.bin_fits_df(fits_df, bin_size=bin_size)
binned_df

In [ ]:
period = binned_df.index[1] - binned_df.index[0]
period

In [ ]:
trapallada.plot.df(binned_df, columns=[pathlib.Path(e).stem for e in binned_df.columns], index_type='T')

In [ ]:
binned_df

In [ ]:
sliced_signals, sliced_times = trapallada.xsa.util.slice(binned_df, window_size=90, step=50, tail_as_window=False)
sliced_signals.shape

In [ ]:
sliced_signals[3]

In [ ]:
trapallada.plot.signals_array(sliced_signals)

In [ ]:
# signals, metadata_df = trapallada.xsa.util.tars_to_array(tar_files[:5])
signals, metadata_df = trapallada.xsa.util.tars_to_array(tar_files)

In [ ]:
metadata_df.head()

The base name for the output files...

In [ ]:
output_file_stem = '35000_45000'

...to be saved

In [ ]:
torch.save(torch.from_numpy(np.expand_dims(signals, 1)), (output_directory / (output_file_stem + '_signals')).with_suffix('.pt'))
metadata_df.to_parquet((output_directory / (output_file_stem + '_metadata')).with_suffix('.parquet'))

A *PyTorch* `Dataset` is built

In [ ]:
ds = trapallada.data.SignalsDataset(
    (output_directory / (output_file_stem + '_signals')).with_suffix('.pt'),(output_directory / (output_file_stem + '_metadata')).with_suffix('.parquet'), normalize=True)

A particular sample

In [ ]:
i = 10
print(ds[i])
trapallada.plot.signal(ds[i][1][0])